<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="lidar_radius" value="0.035" />
    <xacro:property name="lidar_height" value="0.042" />
    <xacro:property name="two_d_lidar_sample_size" value="361"/>
    <xacro:property name="two_d_lidar_min_angle" value="-180"/>
    <xacro:property name="two_d_lidar_max_angle" value="180"/>
    <xacro:property name="two_d_lidar_min_range" value="0.12"/>
    <xacro:property name="two_d_lidar_max_range" value="3.5"/>

    <link name="lidar_link">
        <visual>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_height}" />
            </geometry>
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_height}" />
            </geometry>
        </collision>
        <xacro:cylinder_inertia m="0.131" r="${lidar_radius}" h="${lidar_height}"
                           xyz="0 0 0" rpy="0 0 0" />
    </link>

    <joint name="lidar_joint" type="fixed">
        <parent link="base_link"/>
        <child link="lidar_link" />
        <origin xyz="${base_length / 3.0} 0 ${base_height + lidar_height / 2.0}" rpy="0 0 0" />
    </joint>

    <gazebo reference="lidar_link">
        <gravity>true</gravity>
        <sensor name="lidar_sensor" type="ray">
            <!-- ensure the sensor is active (required) -->
            <always_on>true</always_on>
            <update_rate>5</update_rate>
            <visualize>true</visualize>
            <enable_metrics>true</enable_metrics>
            <ray>
                <scan>
                    <horizontal>
                        <samples>${two_d_lidar_sample_size}</samples>
                        <resolution>1</resolution>
                        <min_angle>${radians(two_d_lidar_min_angle)}</min_angle>
                        <max_angle>${radians(two_d_lidar_max_angle)}</max_angle>
                        <min_intensity>100.0</min_intensity>
                    </horizontal>
                </scan>
                <range>
                    <min>${two_d_lidar_min_range}</min>
                    <max>${two_d_lidar_max_range}</max>
                    <resolution>0.015</resolution>
                </range>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.01</stddev>
                </noise>
            </ray>
            <plugin name="gazebo_ros_laser" filename="libgazebo_ros_ray_sensor.so">
                <ros>
                    <output>screen</output>
                    <remapping>~/out:=/scan</remapping>
                </ros>
                <output_type>sensor_msgs/LaserScan</output_type>
            </plugin>
        </sensor>
    </gazebo>
</robot>